### ISSUE TITLE
Google auth - Internal Server Error - System.NullReferenceException

### ISSUE THREAD

**Issue by danielloczi** [Azure/azure-mobile-apps-net-server#134]
Server Errors appeared a couple of days ago, and still facing this problem. I haven't changed the deployment since a while, so I guess something changed on the Azure service side.
Checking the logstream it seems, that something wrong with Google authentication. Other providers (Facebook, Twitter, MS) work fine.

Here is an extract from the logs:

```
 95 2016-06-05T16:26:25  PID[3260] Verbose     Received request: GET https://******.azurewebsites.net/.auth/login/google
 96 2016-06-05T16:26:25  PID[3260] Information Redirecting: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=*******-*********.apps.googleusercontent.com&redirect_uri=https%3A%2F%2F******.azurewebsites.net%2F.auth%2Flogin%2Fgoogle%2Fcallback&scope=openid+profile+email&state=nonce%***************_**********************%26redir%3D
 97 2016-06-05T16:26:25  PID[3260] Verbose     Received request: GET https://*********.azurewebsites.net/.auth/login/google/callback?state=nonce%*********_******%26redir%3D&code=**********************************&authuser=0&session_state=*****************ae18bcb31..9650&prompt=none
 98 2016-06-05T16:26:25  PID[3260] Verbose     Calling into external HTTP endpoint POST https://www.googleapis.com/oauth2/v4/token.
 99 2016-06-05T16:26:25  PID[3260] Critical    System.NullReferenceException: Object reference not set to an instance of an object.
100    at Microsoft.Azure.AppService.Authentication.GoogleProvider.<UpdateTokenStoreAsync>d__44.MoveNext()
101 --- End of stack trace from previous location where exception was thrown ---
102    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
103    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
104    at Microsoft.Azure.AppService.Authentication.GoogleProvider.<HandleServerDirectedLoginAsync>d__4.MoveNext()
105 --- End of stack trace from previous location where exception was thrown ---
106    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
107    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
108    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
109    at Microsoft.Azure.AppService.Authentication.IdentityProviderBase.<OnCompleteServerDirectedLoginAsync>d__18.MoveNext()
110 --- End of stack trace from previous location where exception was thrown ---
111    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
112    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
113    at Microsoft.Azure.AppService.Authentication.IdentityProviderBase.<TryHandleProtocolRequestAsync>d__0.MoveNext()
114 --- End of stack trace from previous location where exception was thrown ---
115    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
116    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
117    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
118    at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<OnBeginRequestAsync>d__0.MoveNext()
119 --- End of stack trace from previous location where exception was thrown ---
120    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
121    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
122    at Microsoft.Azure.AppService.Authentication.HttpModuleDispatcher.<DispatchAsync>d__13.MoveNext()
123 2016-06-05T16:26:25  PID[3260] Information Sending response: 500.79 Internal Server Error
```

The Microsoft.Azure.Mobile.Server package version is v1.1.157.1

Could you please check this?

**Comment by cgillum** [comment]
A recent App Service platform update has been recently applied to a subset of clusters worldwide. We're investigating to see if it may have impacted Google authentication.

**Comment by danielloczi** [comment]
Thanks for the feedback!
Yes, that is the case: only brand new Google users are affected.

**Comment by chadiswar** [comment]
Seeing the same issue within my deployment.  Has the fix been deployed and will it require a redeployment of our backend?

**Comment by eduandres01** [comment]
Hi, I have the same issue. it is possible to fix it?
Thanks!

**Comment by cgillum** [comment]
The fix has been deployed to many of our clusters already, but there are still a few which don't have it. All our scale units worldwide should have the fix in the next day or two. A redeployment will **not** be required.

**Comment by chadiswar** [comment]
Thank you for clarification.

**Comment by eduandres01** [comment]
Google auth is ok now, but when set the current user via
client.CurrentUser = new MobileServiceUser("theuserid");
client.CurrentUser.MobileServiceAuthenticationToken = "token";

The backend say that this.User.Identity.IsAuthenticated is false, yesterday the same code say that true
Is a azure bug?
