### ISSUE TITLE
Upgrade WindowsAzure.Storage to 6.1.0 will break TableController<TData>.UpdateAsync

### ISSUE THREAD

**Issue by eNeRGy164** [Azure/azure-mobile-apps-net-server#16]
After upgrading the NuGet package for WindowsAzure.Storage from 6.0.0 to 6.1.0 updates to my data result in an error 500. Downgrading fixes the error.
I've switch multiple times between NuGet versions and the error is consistent with version 6.1.0.

The server side exception is:
```
Method not found: 'Microsoft.WindowsAzure.Storage.Table.TableOperation Microsoft.WindowsAzure.Storage.Table.TableOperation.Retrieve(System.String, System.String)'.
```

StackTrace:
```
at Microsoft.Azure.Mobile.Server.StorageDomainManager`1.<GetCurrentItem>d__27.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Mobile.Server.StorageDomainManager`1.GetCurrentItem(CompositeTableKey key, Boolean includeDeleted)
   at Microsoft.Azure.Mobile.Server.StorageDomainManager`1.<UpdateAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Mobile.Server.TableController`1.<PatchAsync>d__12.MoveNext()
```

**Comment by mattchenderson** [comment]
Acknowledged. Thanks for finding this.

**Comment by petersondrew** [comment]
This appears to still be an issue as I'm running into it now (WindowsAzure.Storage v7)
