### ISSUE TITLE
Exception from AutoMapper after publishing new build

### ISSUE THREAD

**Issue by maxsieben** [Azure/azure-mobile-apps-net-server#184]
I am using the newest server nuget packages 2.0.0 like Microsoft.Azure.Mobile.Server.
The following message appears in my app service logs, once every time I publish a new build:

Warning     Message='Exception thrown while getting types from 'AutoMapper.Net4, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'.', Exception=System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.Web.Http.Tracing.Tracers.DefaultHttpControllerTypeResolverTracer.GetTypesAndTrace(Assembly assembly)

However everythings works as expected, but maybe its better to fix this exception?
Maybe there is a problem because I use the newest AutoMapper 5.2.0?

**Comment by maxsieben** [comment]
It seems that the old AutoMapper.Net4.dll was in the bin folder on the server. I deleted this, now there no more errors.
