### ISSUE TITLE
Error when running unit tests

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-net-server#207]
Running on VS2017

```
[xUnit.net 00:00:12.2655709]   Discovering: Microsoft.Azure.Mobile.Server.Tables.Test
[xUnit.net 00:00:14.6000977] Microsoft.Azure.Mobile.Server.Tables.Test: Error creating Visual Studio test case for CreateContract_CallsGetContractOnDeltaTypes(input: typeof(System.Web.Http.OData.Delta<System.Uri>)): System.ArgumentException: We cannot serialize type System.Uri because it lives in the GAC
Parameter name: type

Server stack trace: 
   at Xunit.Sdk.SerializationHelper.GetTypeNameForSerialization(Type type) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 196
   at Xunit.Sdk.SerializationHelper.<>c.<GetTypeNameForSerialization>b__5_0(Type t) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 215
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xunit.Sdk.SerializationHelper.GetTypeNameForSerialization(Type type) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 215
   at Xunit.Serialization.XunitSerializationInfo.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 286
   at Xunit.Serialization.XunitSerializationInfo.SerializeTriple(XunitSerializationTriple triple) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 73
   at Xunit.Serialization.XunitSerializationInfo.<>c.<ToSerializedString>b__5_0(KeyValuePair`2 kvp) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xunit.Serialization.XunitSerializationInfo.ToSerializedString() in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
   at Xunit.Serialization.XunitSerializationInfo.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 301
   at Xunit.Serialization.XunitSerializationInfo.SerializeTriple(XunitSerializationTriple triple) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 73
   at Xunit.Serialization.XunitSerializationInfo.<>c.<ToSerializedString>b__5_0(KeyValuePair`2 kvp) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xunit.Serialization.XunitSerializationInfo.ToSerializedString() in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
   at Xunit.Sdk.SerializationHelper.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 64
   at Xunit.Sdk.TestFrameworkDiscoverer.Serialize(ITestCase testCase) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 195
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFrameworkDiscoverer.Serialize(ITestCase testCase)
   at Xunit.Xunit2Discoverer.Serialize(ITestCase testCase)
   at Xunit.XunitFrontController.Serialize(ITestCase testCase)
   at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoveryVisitor.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueNames, LoggerHelper logger, HashSet`1 knownTraitNames)
```

**Comment by pvbchak** [comment]
It's an issue in Xunit [#777](https://github.com/xunit/xunit/issues/777)
