### ISSUE TITLE
APNS blade not working 

### ISSUE THREAD

**Issue by shiranGinige** [Azure/azure-mobile-apps-net-server#223]
Steps to reproduce : 

Navigate to Notification Hub -> Notification Services -> APNS 
It keeps on loading. 

When looked at the console, following errors are there. 

> 
> 
> MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46 [Microsoft_Azure_NotificationHubs]  23:00:13 MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Code: 'observablePathInvalid'. 
> stack: Error: Code: 'observablePathInvalid'. 
>     at Object.t.(anonymous function) [as observablePathInvalid] (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:21:670)
>     at o (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:387:161)
>     at t (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:388:500)
>     at Object.getOriginalObservable (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:389:656)
>     at read (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:382:649)
>     at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:727)
>     at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:273)
>     at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:787)
>     at Function.evaluatePossiblyAsync (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:391)
>     at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:125:195)
> 
> r @ MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46
> 2/api/Telemetry Failed to load resource: net::ERR_CONNECTION_RESET
> 5/api/Settings/Update Failed to load resource: net::ERR_CONNECTION_RESET
> MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46 [Microsoft_Azure_NotificationHubs]  23:00:28 MsPortalFx.ViewModels.Forms.EditScopeAccessors.InvalidObservablePath MsPortalFx.ViewModels.Forms.EditScopeAccessors.InvalidObservablePath: 'observablePath' does not identify a non-null observable (observablePath: properties.gcmCredential.properties.googleApiKey).
> r @ MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46
> MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46 [Microsoft_Azure_NotificationHubs]  23:00:33 MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Code: 'observablePathInvalid'. 
> stack: Error: Code: 'observablePathInvalid'. 
>     at Object.t.(anonymous function) [as observablePathInvalid] (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:21:670)
>     at o (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:387:161)
>     at t (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:388:500)
>     at Object.getOriginalObservable (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:389:656)
>     at read (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:382:649)
>     at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:727)
>     at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:273)
>     at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:787)
>     at Function.evaluatePossiblyAsync (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:391)
>     at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:125:195)
> 
> r @ MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46
> 2/api/Telemetry Failed to load resource: net::ERR_CONNECTION_RESET
> management.azure.com/batch?api-version=2015-11-01 Failed to load resource: net::ERR_CONNECTION_RESET
> MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46 [Microsoft_Azure_NotificationHubs]  23:39:31 MsPortalFx.ViewModels.Forms.EditScopeAccessors.InvalidObservablePath MsPortalFx.ViewModels.Forms.EditScopeAccessors.InvalidObservablePath: 'observablePath' does not identify a non-null observable (observablePath: properties.apnsCredential.properties.endpoint).
> r @ MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46
> MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46 [Microsoft_Azure_NotificationHubs]  23:39:38 MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Code: 'observablePathInvalid'. 
> stack: Error: Code: 'observablePathInvalid'. 
>     at Object.t.(anonymous function) [as observablePathInvalid] (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:21:670)
>     at o (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:387:161)
>     at t (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:388:500)
>     at Object.getOriginalObservable (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:389:656)
>     at read (https://portal.azure.com/Content/Dynamic/MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:382:649)
>     at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:727)
>     at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:136:273)
>     at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:787)
>     at Function.evaluatePossiblyAsync (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:135:391)
>     at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/MsPortalFxStable_E77384E18787B4B0B69F3A9A106AC50F45FE8CC9.js:125:195)
> 
> r @ MsPortalFx_1BEF18A65F6D4B349DBE50CD6C5EC310794A84F8.js:46
> s2.notificationhubs.ext.azure.com/api/ClientTrace?region=eastasia&cacheVers…ion=5.0.302.50504.150715-1243&l=en.en-gb&trustedAuthority=portal.azure.com Failed to load resource: net::ERR_CONNECTION_RESET
> management.azure.com/subscriptions/17bd5787-ffbc-4ae0-88d2-e94863ffbe5d/res…rs/Microsoft.NotificationHubs/namespaces/flive-prod?api-version=2017-04-01 Failed to load resource: net::ERR_TIMED_OUT
> management.azure.com/batch?api-version=2015-11-01 Failed to load resource: net::ERR_CONNECTION_RESET
> management.azure.com/subscriptions/17bd5787-ffbc-4ae0-88d2-e94863ffbe5d/res…ive-prod/notificationHubs/flive-prod/pnsCredentials?api-version=2017-04-01 Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by shiranGinige** [comment]
This is fixed now. Thanks guys!
