### ISSUE TITLE
Custom Auth not working anymore

### ISSUE THREAD

**Issue by alexrysgspr** [Azure/azure-mobile-apps-net-server#249]
Custom auth codes work perfectly locally. But when I upload it in azure and try accessing the protected controller it says "The page cannot be displayed because an internal server error has occurred." when x-zumo-auth contains correct token. But when I try to put wrong token it says Authorization denied.

Source code :
https://github.com/alexrysgspr/TestCustomAuth

**Comment by MatkovIvan** [comment]
Hi @alexrysgspr,

Could you please attach the server's logs with error? You can enable and view the logs right in the azure portal.
It will contain information about which error occurred.

**Comment by alexrysgspr** [comment]
@MatkovIvan Here it is.
2018-09-20T07:57:55  PID[3976] Critical    System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<HydrateTokenStoreUserClaimsAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<AuthenticateAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<OnAuthenticateRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.HttpModuleDispatcher.<DispatchAsync>d__10.MoveNext()

**Comment by jwallra** [comment]
This error actually comes from the Azure Websites Easy Auth backend.  Please open an [Azure support ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

If you're interested, we have more documentation about custom auth [here](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/).
